services:
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: chandelier-store-database
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${database_user}
      POSTGRES_PASSWORD: ${database_password}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${database_user} -d chandelier_store_catalog"]
      interval: 50s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "${database_port}:${database_port}"
    networks:
      - chandelier-store-network

  gateway:
    image: chandelier-store-gateway
    container_name: chandelier-store-gate
    build:
      context: ./microservices/
      dockerfile: ./microservices.ApiGateway/Dockerfile
    ports:
      - "9200:9200"
    environment:
      ASPNETCORE_HTTP_PORTS: 9200
      ASPNETCORE_ENVIRONMENT: Release
    networks: 
      - chandelier-store-network

  supplyAPI:
    image: chandelier-store-supplyapi
    container_name: chandelier-store-supply
    build:
      context: ./microservices/
      dockerfile: ./microservice.SupplyAPI/Dockerfile
    ports:
      - "9210:9210"
    environment:
      ASPNETCORE_HTTP_PORTS: 9210
      ConnectionStrings__DefaultConnection: "User ID=${database_user};Password=${database_password};Host=${database_host};Port=${database_port};Database=chandelier_store_supply;"
      ASPNETCORE_ENVIRONMENT: Release
    networks:
      - chandelier-store-network

  catalogAPI:
    image: chandelier-store-catalogapi
    container_name: chandelier-store-catalog
    build:
      context: ./microservices/
      dockerfile: ./microservices.CatalogAPI/Dockerfile
    ports:
      - "9220:9220"
    environment:
      ASPNETCORE_HTTP_PORTS: 9220
      ConnectionStrings__DefaultConnection: "User ID=${database_user};Password=${database_password};Host=${database_host};Port=${database_port};Database=chandelier_store_catalog;"
      ASPNETCORE_ENVIRONMENT: Release
    networks:
      - chandelier-store-network

  userAPI:
    image: chandelier-store-userapi
    container_name: chandelier-store-user
    build:
      context: ./microservices/
      dockerfile: ./microservices.UserAPI/Dockerfile
    ports:
      - "9230:9230"
    environment:
      ASPNETCORE_HTTP_PORTS: 9230
      ConnectionStrings__DefaultConnection: "User ID=${database_user};Password=${database_password};Host=${database_host};Port=${database_port};Database=chandelier_store_user;"
      ASPNETCORE_ENVIRONMENT: Release
    networks:
      - chandelier-store-network

  nginx:
    image: nginx:alpine3.22
    container_name: chandelier-store-nginx
    ports:
      - "8100:8100"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - chandelier-store-network

  frontend:
    image: chandelier-store-frontend
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    networks:
      - chandelier-store-network

volumes:
  postgres:

networks:
  chandelier-store-network:
    driver: bridge
