services:
  catalogAPI:
    image: chandelier-store-catalogapi
    container_name: chandelier-store-catalog
    build:
      context: ../../microservices/
      dockerfile: ./microservices.CatalogAPI/Dockerfile
    ports:
      - "5176:5176"
      - "5178:5178"
    environment:
      ASPNETCORE_HTTP_PORTS: 5176
      ConnectionStrings_DefaultConnection: User ID={database_user};Password={database_password};Host={database_host};Port={database_port};Database=chandelier_store_catalog;
      ASPNETCORE_ENVIRONMENT: Development

  userAPI:
    image: chandelier-store-userapi
    container_name: chandelier-store-user
    build:
      context: ../../microservices/
      dockerfile: ./microservices.UserAPI/Dockerfile
    ports:
      - "5166:5166"
      - "5168:5168"
    environment:
      ASPNETCORE_HTTP_PORTS: 5166
      ConnectionStrings_DefaultConnection: User ID={database_user};Password={database_password};Host={database_host};Port={database_port};Database=chandelier_store_user;
      ASPNETCORE_ENVIRONMENT: Development

  supplyAPI:
    image: chandelier-store-supplyapi
    container_name: chandelier-store-supply
    build:
      context: ../../microservices/
      dockerfile: ./microservice.SupplyAPI/Dockerfile
    ports:
      - "5156:5156"
      - "5158:5158"
    environment:
      ASPNETCORE_HTTP_PORTS: 5156
      ConnectionStrings_DefaultConnection: User ID={database_user};Password={database_password};Host={database_host};Port={database_port};Database=chandelier_store_supply;
      ASPNETCORE_ENVIRONMENT: Development